// Inlines src/styles.css into src/index.html and writes the result to index.html at the repo root.
// Pagecrypt needs one self-contained file, so the stylesheet cannot stay external.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("./", import.meta.url);
const htmlUrl = new URL("src/index.html", root);
const cssUrl = new URL("src/styles.css", root);
const outUrl = new URL("index.html", root);

const LINK_TAG = /^([ \t]*)<link rel="stylesheet" href="styles\.css">[ \t]*$/m;

const [html, css] = await Promise.all([
  readFile(htmlUrl, "utf8"),
  readFile(cssUrl, "utf8"),
]);

if (!LINK_TAG.test(html)) {
  throw new Error('No <link rel="stylesheet" href="styles.css"> found in src/index.html');
}

if (/<\/style/i.test(css)) {
  throw new Error("src/styles.css contains a </style sequence, which would break the inlined block");
}

const output = html.replace(LINK_TAG, (_match, indent) => {
  const body = css.trimEnd().replace(/^(?=.)/gm, indent + "  ");
  return `${indent}<style>\n${body}\n${indent}</style>`;
});

const banner = "<!-- Generated by build.mjs. Edit src/index.html and src/styles.css instead. -->\n";

await writeFile(outUrl, banner + output, "utf8");

console.log(`Wrote ${fileURLToPath(outUrl)}`);
